
export const GET_ALL_Courses = "GET_ALL_Courses"
export const CREATE_Course = "CREATE_Course"
export const GET_ERROR = "GET_ERROR"
export const GET_COURSE_DETAILS = "GET_COURSE_DETAILS"

export const GET_ALL_WHAT_YOU_WILL_LEARN = "GET_ALL_WHAT_YOU_WILL_LEARN"
export const GET_THIS_COURSE_INCLUDES="GET_THIS_COURSE_INCLUDES"
export const GET_COURSE_INFO="GET_COURSE_INFO"
export const GET_CART_COURSES="GET_CART_COURSES"
export const GET_THIS_COURSE_REQUIRMENTS="GET_THIS_COURSE_REQUIRMENTS"