
export const GET_ALL_Courses = "GET_ALL_Courses"
export const CREATE_Course = "CREATE_Course"
export const GET_ERROR = "GET_ERROR"
export const GET_COURSE_DETAILS = "GET_COURSE_DETAILS"

export const GET_ALL_WHAT_YOU_WILL_LEARN = "GET_ALL_WHAT_YOU_WILL_LEARN"
export const GET_THIS_COURSE_INCLUDES="GET_THIS_COURSE_INCLUDES"
export const GET_COURSE_INFO="GET_COURSE_INFO"
export const GET_CART="GET_CART"
export const GET_THIS_COURSE_REQUIRMENTS="GET_THIS_COURSE_REQUIRMENTS"

export const GET_SEARCH_TERM = "GET_SEARCH_TERM"
export const UPDATE_SARCH_TERM = "UPDATE_SEARCH_TERM"
export const GET_INSTRUCTOR_PROFILE="GET_INSTRUCTOR_PROFILE"
export const GET_COURSE_REVIEWS="GET_COURSE_REVIEWS"

export const GET_USER_DATA = "GET_USER_DATA"
export const GET_LOGGED_USER_DATA = "GET_LOGGED_USER_DATA"
export const LOGOUT = "LOGOUT"

export const SET_USER_LOADING = "SET_USER_LOADING"

export const SET_ADMIN_LOADING = "SET_ADMIN_LOADING"

export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_ERROR_ORDERS = "GET_ERROR_ORDERS"

export const GET_PROFILE_DATA = "GET_PROFILE_DATA"
export const GET_ORDERS = "GET_ORDERS"